server:
  port: 8088

spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/note_master?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: uAiqwVwjJ8-i
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 20
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/note_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: uAiqwVwjJ8-i
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 20
  #redis配置
  redis:
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms #连接超时时间（毫秒）
#      host: 127.0.0.1 #Redis服务器地址  #单例用这个配置
#      port: 6379  #Redis服务器连接端口
    cluster:  #集群用这个配置
      nodes:
        - 10.105.10.37:6380
        - 10.105.10.37:6381
        - 10.105.10.37:6382
        - 10.105.10.37:6383
        - 10.105.10.37:6384
        - 10.105.10.37:6385
      max-redirects: 2 #获取失败 最大重定向次数
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接


mybatis:
  mapper-locations: classpath:com/sh/mapper/*.xml
  type-aliases-package: com.sh.entity


logging:
  level:
    com.sh.dao: DEBUG

note:
  printExp: true # 是否控制台输出异常信息