server:
  port: 8081

spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/note_master?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 20
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/note_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 20

#mybatis:
#  mapper-locations: classpath:com/sh/mapper/*.xml
#  type-aliases-package: com.sh.entity


logging:
  level:
    com.sh.dao : DEBUG

note:
  printExp: false # 是否控制台输出异常信息

